---
- name: Perform yum update of all packages
  yum:
    name: '*'
    state: latest

- name: Import Jenkins Key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    state: present

- name: Add Jenkins RPM Repo
  yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: true

- name: Install Java
  yum:
    name: java-11-openjdk-devel
    state: present
    update_cache: true

- name: Install Epel-Release
  yum:
    name: epel-release
    state: present
    update_cache: true

- name: Install Daemonize
  yum:
    name: daemonize
    state: present
    update_cache: true

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
    update_cache: true

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes
